<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tendai Gwanzura">
<meta name="dcterms.date" content="2025-06-25">

<title>Modellers and Story Tellers: Group 2 project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Programeval_HoFoCo_files/libs/clipboard/clipboard.min.js"></script>
<script src="Programeval_HoFoCo_files/libs/quarto-html/quarto.js"></script>
<script src="Programeval_HoFoCo_files/libs/quarto-html/popper.min.js"></script>
<script src="Programeval_HoFoCo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Programeval_HoFoCo_files/libs/quarto-html/anchor.min.js"></script>
<link href="Programeval_HoFoCo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Programeval_HoFoCo_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Programeval_HoFoCo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Programeval_HoFoCo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Programeval_HoFoCo_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modellers and Story Tellers: Group 2 project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tendai Gwanzura </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 25, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="hollywood-coalition-data-cleaning-and-analysis." class="level2">
<h2 class="anchored" data-anchor-id="hollywood-coalition-data-cleaning-and-analysis.">Hollywood coalition data cleaning and analysis.</h2>
<p>This file contains the data cleaning and data analysis for Hollywood Food Coalition an organization aimimg to reduce food insecurity in Los Angeles.</p>
<p>.</p>
</section>
<section id="install-and-load-libaries" class="level2">
<h2 class="anchored" data-anchor-id="install-and-load-libaries">Install and load libaries</h2>
<p>install.packages(“readxl”) install.packages(“openxlsx”) install.packages(“dplyr”) install.packages(“ggplot2”) install.packages(“janitor”) install.packages(“tidyr”) install.packages(“stringr”)<br>
install.packages(“tidytext”) install.packages(“topicmodels”) install.packages(“wordcloud”) install.packages(“RColorBrewer”)</p>
</section>
<section id="load-and-prepare-the-data" class="level1">
<h1>Load and Prepare the Data</h1>
<p>Use read_excel to load data, after removing encryption in excel and rename new file to HFC_2025. For password openxlsx does not work despite having the password option.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>HFC_2025 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"HFC _2025.xlsx"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(HFC_2025)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HFC_2025)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Org ID"                                     
 [2] "Orgs"                                       
 [3] "Date"                                       
 [4] "Organization Type"                          
 [5] "Location"                                   
 [6] "Hours of Operation"                         
 [7] "On Site Contact"                            
 [8] "Metrics"                                    
 [9] "Volunteer Run Organization"                 
[10] "Unique individuals served weekly"           
[11] "Total served weekly"                        
[12] "Unique individuals served monthly"          
[13] "Total served monthly"                       
[14] "Age range of population served"             
[15] "Racial makeup of population served"         
[16] "Percentage of low income population served" 
[17] "(Under 18) Population Percentage"           
[18] "(18-25) Population Percentage"              
[19] "(26-40) Population Percentage"              
[20] "(41-65) Population Percentage"              
[21] "(65+) Population Percentage"                
[22] "Population Languages"                       
[23] "(Male) Gender Make Up"                      
[24] "(Female) Gender Make Up"                    
[25] "(Non-Binary) Gender Make Up"                
[26] "(Transgender) Gender Make Up"               
[27] "Veterans served"                            
[28] "Previously Incarcerated"                    
[29] "LBGTQ+"                                     
[30] "Unhoused"                                   
[31] "Program Entry/Food restrictions"            
[32] "Primary Demographics"                       
[33] "Primary Services"                           
[34] "Services Offered"                           
[35] "Referrals accepted"                         
[36] "Typical individual Seeking Service"         
[37] "Outcome Goals"                              
[38] "Service Locations"                          
[39] "Recent Changes"                             
[40] "Meeting Recent Changes"                     
[41] "1 Year Growth Plans"                        
[42] "5 Year Growth Plans"                        
[43] "Holidays Recognized"                        
[44] "Other Schedule Notes"                       
[45] "Preferred Food Items"                       
[46] "Most to Least Desired"                      
[47] "Reason for Originally Partnering"           
[48] "Reason for Continued Partnership"           
[49] "Food Sources"                               
[50] "Food Intake Barriers"                       
[51] "(Hypothetical) Food Response without Hofoco"
[52] "(Hypothetical) Hofoco Food Delivery Option" 
[53] "Recent Food Quality"                        
[54] "Food Quality"                               
[55] "Impact of Food Received"                    
[56] "Impact Story (1)"                           
[57] "Impact Story (2)"                           
[58] "Impact Story (3)"                           
[59] "Food Distro Process"                        
[60] "Food Distro Challenges"                     
[61] "Feedback"                                   
[62] "Notes"                                      
[63] "Future Check In Preference"                 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total unique individuals served weekly</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(HFC_2025<span class="sc">$</span><span class="st">'Unique individuals served weekly'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  20.00   85.25  185.00  315.23  312.50 3500.00       2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total individuals served monthly</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(HFC_2025<span class="sc">$</span><span class="st">'Unique individuals served monthly'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   40.0   132.5   300.0   417.4   500.0  2000.0       3 </code></pre>
</div>
</div>
<p>The variable names contain spaces hence will need to be cleaned using the janitor package creating a new data set HFC_2025_clean.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "org_id"                                    
 [2] "orgs"                                      
 [3] "date"                                      
 [4] "organization_type"                         
 [5] "location"                                  
 [6] "hours_of_operation"                        
 [7] "on_site_contact"                           
 [8] "metrics"                                   
 [9] "volunteer_run_organization"                
[10] "unique_individuals_served_weekly"          
[11] "total_served_weekly"                       
[12] "unique_individuals_served_monthly"         
[13] "total_served_monthly"                      
[14] "age_range_of_population_served"            
[15] "racial_makeup_of_population_served"        
[16] "percentage_of_low_income_population_served"
[17] "under_18_population_percentage"            
[18] "x18_25_population_percentage"              
[19] "x26_40_population_percentage"              
[20] "x41_65_population_percentage"              
[21] "x65_population_percentage"                 
[22] "population_languages"                      
[23] "male_gender_make_up"                       
[24] "female_gender_make_up"                     
[25] "non_binary_gender_make_up"                 
[26] "transgender_gender_make_up"                
[27] "veterans_served"                           
[28] "previously_incarcerated"                   
[29] "lbgtq"                                     
[30] "unhoused"                                  
[31] "program_entry_food_restrictions"           
[32] "primary_demographics"                      
[33] "primary_services"                          
[34] "services_offered"                          
[35] "referrals_accepted"                        
[36] "typical_individual_seeking_service"        
[37] "outcome_goals"                             
[38] "service_locations"                         
[39] "recent_changes"                            
[40] "meeting_recent_changes"                    
[41] "x1_year_growth_plans"                      
[42] "x5_year_growth_plans"                      
[43] "holidays_recognized"                       
[44] "other_schedule_notes"                      
[45] "preferred_food_items"                      
[46] "most_to_least_desired"                     
[47] "reason_for_originally_partnering"          
[48] "reason_for_continued_partnership"          
[49] "food_sources"                              
[50] "food_intake_barriers"                      
[51] "hypothetical_food_response_without_hofoco" 
[52] "hypothetical_hofoco_food_delivery_option"  
[53] "recent_food_quality"                       
[54] "food_quality"                              
[55] "impact_of_food_received"                   
[56] "impact_story_1"                            
[57] "impact_story_2"                            
[58] "impact_story_3"                            
[59] "food_distro_process"                       
[60] "food_distro_challenges"                    
[61] "feedback"                                  
[62] "notes"                                     
[63] "future_check_in_preference"                </code></pre>
</div>
</div>
<p>We can see a summary of the individuals served weekly and monthly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(HFC_2025_clean<span class="sc">$</span>unique_individuals_served_weekly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  20.00   85.25  185.00  315.23  312.50 3500.00       2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(HFC_2025_clean<span class="sc">$</span>total_served_weekly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    0.0   100.0   165.0   318.3   387.5  2100.0       2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(HFC_2025_clean<span class="sc">$</span>unique_individuals_served_monthly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   40.0   132.5   300.0   417.4   500.0  2000.0       3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(HFC_2025_clean<span class="sc">$</span>total_served_monthly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      0     376     625    1697    1550   20000       2 </code></pre>
</div>
</div>
</section>
<section id="age-and-gender-distribution-across-all-organizations" class="level1">
<h1>Age and gender distribution across all organizations</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  under_18 age_18_25 age_26_40 age_41_65 age_65_plus
     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
1   0.0609     0.172     0.325     0.325       0.126</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/age_summary-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On average, 6.1% of individuals served across all organizations are under 18. Around 17.2% of individuals are young adults (18–25). About 32.5% are adults aged 26–40. About 32.5% are middle-aged to older adults (41–65). Around 12.6% are seniors, aged 65 and above.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
   male female non_binary transgender
  &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;
1 0.543  0.415      0.022      0.0565</code></pre>
</div>
</div>
<p>About 54.3% of the individuals served are male.About 41.5% are female.About 2.2% are non-binary. About 5.6% identify as transgender (can overlap with other categories depending on how the data was reported). The following plot shows gender distribution across all partners.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using results from above to plot the gender </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>gender_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Gender =</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>, <span class="st">"Non-binary"</span>, <span class="st">"Transgender"</span>),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Proportion =</span> <span class="fu">c</span>(<span class="fl">0.5432432</span>, <span class="fl">0.4145946</span>, <span class="fl">0.022</span>, <span class="fl">0.05645161</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gender_data, <span class="fu">aes</span>(<span class="at">x =</span> Gender, <span class="at">y =</span> Proportion, <span class="at">fill =</span> Gender)) <span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">accuracy =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gender Distribution of Individuals Served"</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Proportion"</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/gender_plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The following shows the distribution of the different populations in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pop_focus <span class="ot">&lt;-</span> HFC_2025_clean <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">unhoused =</span> <span class="fu">mean</span>(<span class="fu">as.numeric</span>(unhoused), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lgbtq =</span> <span class="fu">mean</span>(<span class="fu">as.numeric</span>(lbgtq), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">veterans =</span> <span class="fu">mean</span>(<span class="fu">as.numeric</span>(veterans_served), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">previously_incarcerated =</span> <span class="fu">mean</span>(<span class="fu">as.numeric</span>(previously_incarcerated), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>pop_focus</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  unhoused lgbtq veterans previously_incarcerated
     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;                   &lt;dbl&gt;
1    0.657 0.272   0.0667                   0.376</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>pop_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Group =</span> <span class="fu">c</span>(<span class="st">"Unhoused"</span>, <span class="st">"LGBTQ+"</span>, <span class="st">"Veterans"</span>, <span class="st">"Previously Incarcerated"</span>),</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Percentage =</span> <span class="fu">c</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    pop_focus<span class="sc">$</span>unhoused,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    pop_focus<span class="sc">$</span>lgbtq,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    pop_focus<span class="sc">$</span>veterans,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    pop_focus<span class="sc">$</span>previously_incarcerated</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pop_data, <span class="fu">aes</span>(<span class="at">x =</span> Group, <span class="at">y =</span> Percentage)) <span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average % of Vulnerable Populations Served"</span>,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average Percentage"</span>, <span class="at">x =</span> <span class="st">""</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/population_dynamics-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="cleaning-and-plottin-race" class="level1">
<h1>Cleaning and plottin race</h1>
<p>Race contains mixed data that is string and numeric we might need to separate it using the following code.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] NA                                                                    
 [2] "50% Black 50% Brown"                                                 
 [3] "Asian Diaspora/ Pacific Islander"                                    
 [4] "Latino 50%, White 30%, Black 10%, Other 10%"                         
 [5] "white 60%, Latino 25%,. Black 10%, Other 5%"                         
 [6] "White 50%, Latino 30%, Black 20%"                                    
 [7] "White 40%, Black 25%, Latino 20%,  Other 10%, Asian 5%"              
 [8] "Latinos, Whites, Blacks"                                             
 [9] "Black 42%, 35% Latino, 17% White, 15% Other"                         
[10] "60% Filipino, 20% Latino, 10% White, 10% Balck"                      
[11] "Latino 60%, Black 30%, Other 10%"                                    
[12] "Hispanic 44%, Black 35 %, White 21%,"                                
[13] "40% Latino"                                                          
[14] "Latino 50%, White 25%, Black 24%, Asian 1%"                          
[15] "Hispanic 49%, Latino 49%, White 2%"                                  
[16] "Latino 32%, Black 31%, White 29%, Other 8%"                          
[17] "Latino 55%, Armenian 35%, Arab 10%"                                  
[18] "Latino70%, Black 20%, White/Other 10%"                               
[19] "Latino 40%. Black 30%, Other 30%"                                    
[20] "Black, Latino, and Asians"                                           
[21] "Latino 75%, Black 10%, API 5%"                                       
[22] "Latino 75%, Asian 25%,"                                              
[23] "White 35%, Multi 32%, Latino 16%, Black 12%, Other 5%"               
[24] "Armenian/Russian 50%, Latino 40%, Other 10%"                         
[25] "Korean 25%, Black 25%, Latino 25%, Filipino 5%, White 10%, Other 10%"
[26] "88% BIPOC"                                                           
[27] "Latino 86%, Other 14%"                                               
[28] "50% White, 30% Black, 5% Latino, 5% Asian, 10% Other"                
[29] "Black 60%, Latino 30%, White 10%"                                    
[30] "White 50%, Latino 35%, Black 15%,"                                   
[31] "42.5% Brown, 25% Black, 15% White"                                   
[32] "No one race more than another"                                       
[33] "Latino 20%, Asian 80%"                                               
[34] "100% Latino"                                                         
[35] "50% Black, 40% Latino, 10% White"                                    
[36] "50% White, 50% Hispanic"                                             
[37] "Latino 75%, White 10%, Black 5%, API 5%"                             
[38] "Hispanic, Colombian, Salvadorian, Venezulian"                        </code></pre>
</div>
</div>
<p>Important to note not all organizations include the percent of racial makeup they just list the races. The following plot assesses data which contains % makeup of the 38 out of the total 42 organizations without missing data. Filipino, Russian, Armenian and other country specific were set to other for now hence the large percent of other.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>race_summary <span class="ot">&lt;-</span> race_long <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_pct =</span> <span class="fu">mean</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(race_summary, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(group, <span class="sc">-</span>mean_pct), <span class="at">y =</span> mean_pct, <span class="at">fill =</span> group)) <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Racial Composition Across All Organizations"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mean % Served"</span>, <span class="at">x =</span> <span class="st">"Race"</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/plot_race-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/race_plot_each_org-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This visualization highlights how racial representation varies by organization. While Latinx and Black communities are consistently represented, some organizations show a near-exclusive service to one group. This racial composition is important for understanding equity in food access and can inform tailored programming and outreach. Notably, Asian and ‘Other’ populations appear less frequently, which could suggest either demographic realities or potential service gaps. Also not all organizations iclude percent of people affected.</p>
</section>
<section id="plotting-the-reach-and-scale" class="level1">
<h1>Plotting the reach and scale</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> unique_individuals_served_weekly total_served_weekly
 Min.   :  20.00                  Min.   :   0.0     
 1st Qu.:  85.25                  1st Qu.: 100.0     
 Median : 185.00                  Median : 165.0     
 Mean   : 315.23                  Mean   : 318.3     
 3rd Qu.: 312.50                  3rd Qu.: 387.5     
 Max.   :3500.00                  Max.   :2100.0     
 NA's   :2                        NA's   :2          
 unique_individuals_served_monthly total_served_monthly
 Min.   :  40.0                    Min.   :    0       
 1st Qu.: 132.5                    1st Qu.:  376       
 Median : 300.0                    Median :  625       
 Mean   : 417.4                    Mean   : 1697       
 3rd Qu.: 500.0                    3rd Qu.: 1550       
 Max.   :2000.0                    Max.   :20000       
 NA's   :3                         NA's   :2           </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/reach_and_scale-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="qualitative-impact" class="level1">
<h1>Qualitative Impact</h1>
<p>Utilising word cloud to view impact.The default stopwords(“en”) removes general English filler words (like “the”, “is”, “it”). But our text still contains domain-irrelevant or generic words like: guys, week, kids, know, one, used, get, great, makes, just, able, come, etc.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/story_wordcloud-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The most frequent words include:</p>
<p>“food”, “people”, “give”, “quality”, “produce”, “relief”, “nutritious”, “kitchen”, “residents”, “parents”, “love”</p>
<p>The word ‘food’ dominates the stories — underscoring its centrality to service impact.</p>
<p>‘Relief’, ‘quality’, and ‘produce’ point to the value and trust recipients associate with the program.</p>
<p>References to ‘residents’, ‘parents’, and ‘love’ highlight emotional and familial dimensions of food insecurity.</p>
</section>
<section id="we-can-go-further-and-create-themes-based-on-the-words." class="level1">
<h1>We can go further and create themes based on the words.</h1>
<p>For this I chose nutrition, community, empowerment, distribution, emotion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>theme_summary <span class="ot">&lt;-</span> theme_tags <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(nutrition, community, empowerment, distribution, emotion) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">sum</span>(.)))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>theme_summary_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(theme_summary, <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"theme"</span>, <span class="at">values_to =</span> <span class="st">"count"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(theme_summary_long, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(theme, <span class="sc">-</span>count), <span class="at">y =</span> count, <span class="at">fill =</span> theme)) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Stories Matching Each Impact Theme"</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Theme"</span>, <span class="at">y =</span> <span class="st">"Count of Organizations"</span>) <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Note we can go further and do topic modelling but will leave it at themes for now.</p>
</section>
<section id="organization-value-and-resilience" class="level1">
<h1>Organization value and resilience</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>HFC_2025_clean <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(volunteer_run_organization) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> volunteer_run_organization, <span class="at">y =</span> n, <span class="at">fill =</span> volunteer_run_organization)) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Volunteer-Run vs Non-Volunteer Organizations"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Volunteer Run"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/volunteer_orgs-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nearly half of the organizations that HoFoCo works with with are volunteer-run, highlighting a strong reliance on community-driven labor. However, a slightly greater number operate with non-volunteer staffing structures. This suggests a mix of grassroots and institutional capacity within the partner network. The presence of missing values also points to potential opportunities to improve data collection clarity or completeness.”</p>
<section id="text-exploration" class="level2">
<h2 class="anchored" data-anchor-id="text-exploration">Text exploration</h2>
</section>
</section>
<section id="importance-of-hofoco" class="level1">
<h1>Importance of HoFoCo</h1>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/hypothetical_needs-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 97 × 3
   topic term          beta
   &lt;int&gt; &lt;chr&gt;        &lt;dbl&gt;
 1     1 food        0.162 
 2     1 budget      0.0710
 3     1 purchase    0.0579
 4     1 increase    0.0434
 5     1 consistency 0.0434
 6     1 serve       0.0290
 7     1 la          0.0290
 8     1 people      0.0290
 9     1 quality     0.0145
10     1 farmers     0.0145
# ℹ 87 more rows</code></pre>
</div>
</div>
<p>Top 10 keywords: food, budget, purchase, increase, consistency, serve, quality, farmers based on probability values. Now to view all 97 in topics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>top_terms <span class="ot">&lt;-</span> topics <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(topic) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">10</span>, beta) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(topic, <span class="sc">-</span>beta)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(top_terms, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder_within</span>(term, beta, topic), <span class="at">y =</span> beta, <span class="at">fill =</span> <span class="fu">factor</span>(topic))) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> topic, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_reordered</span>() <span class="sc">+</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Top Terms per LDA Topic"</span>,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Term"</span>, <span class="at">y =</span> <span class="st">"Beta (Importance in Topic)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Programeval_HoFoCo_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Using Latent Dirichlet Allocation (LDA), we identified 3 major thematic clusters from open-text responses in the “hypothetical_food_response_without_hofoco” question:</p>
<p>Topic 1: Food Budgeting and Procurement Top terms: food, budget, purchase, consistency, increase, serve, resources, raise, distribute, continue This topic centers around how organizations plan for and manage food procurement, budgeting constraints, and ensuring consistent distribution.</p>
<p>We can label topic as “sustaining Food Supply through Budgeting and Purchasing”</p>
<p>Topic 2: Partner Reliance and Community Coordination Top terms: food, resource, partners, pantry, community, figure, difficult, people This topic shows organizations’ dependence on partner networks, food pantries, and community coordination to address gaps. We can label it community Collaboration and External Resource Navigation</p>
<p>Topic 3: Urgency, Impact, and Emotional Strain Top terms: impact, source, spending, quantity, volume, tremendously, programs, participants, frustration, families, communicate This topic addresses the the emotional and operational impact of food insecurity and limited resources — particularly on participants and families. We can label it emotional and Operational Impact of Insecurity on Families</p>
<p>Note we can do more than 3 themes but for the purpose of presentation I just selected 3.</p>
</section>
<section id="lets-try-to-run-a-regression-next--work-in-progress" class="level1">
<h1>Lets try to run a regression next- work in progress</h1>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>